Update API
mamoe/mirai-console-intellij pull request #15
Opened 2020-06-18 11:18 UTC by Metric-Void

2020-06-18 12:06 UTC, Him188 requested changes

2020-06-18 12:06 UTC, Him188 commented on src/main/java/net/mamoe/mirai/intellij/builder/ContentBuilder.kt
> +                if(gms==null) {
对于来自服务器的消息, 无需检验 null. MessageSource 总是存在.

2020-06-18 17:48 UTC, Metric-Void commented on src/main/java/net/mamoe/mirai/intellij/builder/ContentBuilder.kt
> +                if(gms==null) {
主要是为了抑制Warning

2020-06-19 09:13 UTC, Him188 requested changes

2020-06-19 09:13 UTC, Him188 commented on src/main/java/net/mamoe/mirai/intellij/builder/ContentBuilder.kt
> +                if(gms==null) {
那么应该使用 `Objects.requireNotNull(gms)` 等方法

2020-06-19 10:53 UTC, Him188 approved these changes

2020-06-19 10:54 UTC, merged